# Generated by Django 4.2.6 on 2023-10-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_site_de_emprego', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='vaga',
            name='localidade',
            field=models.CharField(default='05/10/2023', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vaga',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
