# Generated by Django 4.2.6 on 2023-10-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_site_de_emprego', '0002_alter_vaga_localidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='localidade',
            field=models.CharField(max_length=100),
        ),
    ]
