# Generated by Django 4.2.6 on 2023-10-05 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_site_de_emprego', '0002_candidato_conta_empresa_vaga_localidade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidatoFormulario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('p1', models.CharField(max_length=255)),
                ('p2', models.CharField(max_length=255)),
                ('p3', models.CharField(max_length=255)),
                ('p4', models.CharField(max_length=255)),
                ('p5', models.CharField(max_length=255)),
                ('p6', models.CharField(max_length=255)),
                ('p7', models.CharField(max_length=255)),
                ('p8', models.CharField(max_length=255)),
                ('p9', models.CharField(max_length=255)),
                ('p10', models.CharField(max_length=255)),
                ('candidado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_site_de_emprego.candidato')),
            ],
        ),
    ]
