# Generated by Django 4.2.6 on 2023-10-05 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_site_de_emprego', '0003_candidatoformulario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidatoformulario',
            name='candidado',
        ),
    ]
